### ISSUE TITLE
Input doesn't work on OS >=9.0.0

### ISSUE THREAD

**Issue by Camotoy** [MrJPGames/Noodles-#1]
Switch OS 9.0.0 introduced a change in HID where libnx cannot detect button input (see [here](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.9.4)). All it apparently needs is a simple recompile with an updated libnx.

**Comment by MrJPGames** [comment]
Got back some intrest in the switch homebrew scene recently so I decided to update this for the sake of it. Did require more than just updating libnx (the older SDL2 version is not fully compatible with the latest libnx, so that had to be updated as well). However this is now playable on the latest version (and with newer CFW that does not patch in the old HID methods)
